Set up inclusion of python and low-level tests in "make tests" targets

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR HAVE_CHACO_TRUE HAVE_CHACO_FALSE BUILD_TESTS_TRUE BUILD_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE PYTHON_USE_TRUE PYTHON_USE_FALSE PYTHON PYTHON_PREFIX PYTHON_EXECPREFIX BUILD_PYTHON_TRUE BUILD_PYTHON_FALSE PYTHON_CSPEC PYTHON_LSPEC CXXCPP EGREP WITH_SWIG SWIG SWIG_LIB SWIG_PYTHON_OPT SWIG_PYTHON_CPPFLAGS HAVE_SWIG_TRUE HAVE_SWIG_FALSE GNU_HAVE_SWIG ac_aux_dir SUNDANCE_BUILD_DIRECTORY FIAT_STR FIAT_BUILD_DIR SUNDIALS_STR SUNDIALS_BUILD_DIR CHACO_LIB TRILINOS_DIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MPI_CXX HAVE_MPI_TRUE HAVE_MPI_FALSE MPI_CXX_EXISTS MPI_CC_EXISTS MPI_F77_EXISTS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE F77 FFLAGS ac_ct_F77 RANLIB ac_ct_RANLIB USE_ALTERNATE_AR_TRUE USE_ALTERNATE_AR_FALSE ALTERNATE_AR HAVE_CHACO_TRUE HAVE_CHACO_FALSE BUILD_CXXTESTS_TRUE BUILD_CXXTESTS_FALSE BUILD_LOW_LEVEL_TESTS_TRUE BUILD_LOW_LEVEL_TESTS_FALSE BUILD_EXAMPLES_TRUE BUILD_EXAMPLES_FALSE PYTHON_USE_TRUE PYTHON_USE_FALSE PYTHON PYTHON_PREFIX PYTHON_EXECPREFIX BUILD_PYTHON_TRUE BUILD_PYTHON_FALSE PYTHON_CSPEC PYTHON_LSPEC CXXCPP EGREP WITH_SWIG SWIG SWIG_LIB SWIG_PYTHON_OPT SWIG_PYTHON_CPPFLAGS HAVE_SWIG_TRUE HAVE_SWIG_FALSE GNU_HAVE_SWIG ac_aux_dir SUNDANCE_BUILD_DIRECTORY FIAT_STR FIAT_BUILD_DIR SUNDIALS_STR SUNDIALS_BUILD_DIR CHACO_LIB TRILINOS_DIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -880,7 +880,9 @@ Optional Features:
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-chaco          Chaco mesh partitioning
-  --enable-tests          Build tests for Sundance (default is yes)
+  --enable-cxxtests       Build C++ tests for Sundance (default is yes)
+  --enable-lowleveltests  Build low level C++ tests for Sundance (default is
+                          yes)
   --enable-examples       Build examples for Sundance (default is yes)
   --enable-python[=PYTHON]
                           absolute path name of Python executable
@@ -3772,7 +3774,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:3775:" \
+echo "$as_me:3777:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -4238,23 +4240,23 @@ fi
 #  #np# - option(s) that does (do) not apply.
 
 
-# Check whether --enable-tests or --disable-tests was given.
-if test "${enable_tests+set}" = set; then
-  enableval="$enable_tests"
-  ac_cv_use_tests=$enableval
+# Check whether --enable-cxxtests or --disable-cxxtests was given.
+if test "${enable_cxxtests+set}" = set; then
+  enableval="$enable_cxxtests"
+  ac_cv_use_cxxtests=$enableval
 else
-  ac_cv_use_tests=yes
+  ac_cv_use_cxxtests=yes
 fi;
 
-echo "$as_me:$LINENO: checking whether to use tests" >&5
-echo $ECHO_N "checking whether to use tests... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking whether to use cxxtests" >&5
+echo $ECHO_N "checking whether to use cxxtests... $ECHO_C" >&6
 
-if test "X$ac_cv_use_tests" != "Xno"; then
+if test "X$ac_cv_use_cxxtests" != "Xno"; then
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_TESTS
+#define HAVE_CXXTESTS
 _ACEOF
 
 else
@@ -4264,12 +4266,48 @@ fi
 
 
 
-if test "X$ac_cv_use_tests" != "Xno"; then
-  BUILD_TESTS_TRUE=
-  BUILD_TESTS_FALSE='#'
+if test "X$ac_cv_use_cxxtests" != "Xno"; then
+  BUILD_CXXTESTS_TRUE=
+  BUILD_CXXTESTS_FALSE='#'
 else
-  BUILD_TESTS_TRUE='#'
-  BUILD_TESTS_FALSE=
+  BUILD_CXXTESTS_TRUE='#'
+  BUILD_CXXTESTS_FALSE=
+fi
+
+
+
+# Check whether --enable-lowleveltests or --disable-lowleveltests was given.
+if test "${enable_lowleveltests+set}" = set; then
+  enableval="$enable_lowleveltests"
+  ac_cv_use_lowleveltests=$enableval
+else
+  ac_cv_use_lowleveltests=yes
+fi;
+
+echo "$as_me:$LINENO: checking whether to use lowleveltests" >&5
+echo $ECHO_N "checking whether to use lowleveltests... $ECHO_C" >&6
+
+if test "X$ac_cv_use_lowleveltests" != "Xno"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LOW_LEVEL_TESTS
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+if test "X$ac_cv_use_lowleveltests" != "Xno"; then
+  BUILD_LOW_LEVEL_TESTS_TRUE=
+  BUILD_LOW_LEVEL_TESTS_FALSE='#'
+else
+  BUILD_LOW_LEVEL_TESTS_TRUE='#'
+  BUILD_LOW_LEVEL_TESTS_FALSE=
 fi
 
 
@@ -5781,7 +5819,7 @@ fi;
 # Output files
 # ------------------------------------------------------------------------
 
-                                                                                                                                                                                                                                                                                                                                                    ac_config_files="$ac_config_files Makefile Makefile.export Makefile.export.TSFExtended Makefile.site.sundance examples-tutorial/Makefile src-utils/Makefile src-core/Makefile src-std-mesh/Makefile src-std-framework/Makefile src-solvers/Makefile src-std-framework/SundanceDefaultPath.hpp src-xml/Makefile python/Makefile python/src/Makefile python/src/SUNDANCE_HOME_DIR python/src/__init__.py python/src/.deps/dummy python/example/Makefile tests-utils/Makefile tests-utils/Functors/Makefile tests-utils/Maps/Makefile tests-core/Makefile tests-core/SymbolicTests/Makefile tests-solvers/Makefile tests-solvers/VectorTests/Makefile tests-solvers/OperatorTests/Makefile tests-solvers/SolverTests/Makefile tests-std-mesh/Makefile tests-std-mesh/Simple/Makefile tests-std-mesh/Readers/Makefile tests-std-framework/Makefile tests-std-framework/HomogeneousDOFMap/Makefile tests-std-framework/Assembly/Makefile tests-std-framework/Problem/Makefile"
+                                                                                                                                                                                                                                                                                                                                                    ac_config_files="$ac_config_files Makefile Makefile.internal Makefile.export Makefile.export.TSFExtended Makefile.site.sundance examples-tutorial/Makefile src-utils/Makefile src-core/Makefile src-std-mesh/Makefile src-std-framework/Makefile src-solvers/Makefile src-std-framework/SundanceDefaultPath.hpp src-xml/Makefile python/Makefile python/src/Makefile python/src/SUNDANCE_HOME_DIR python/src/__init__.py python/src/.deps/dummy python/example/Makefile tests-utils/Makefile tests-utils/Functors/Makefile tests-utils/Maps/Makefile tests-core/Makefile tests-core/SymbolicTests/Makefile tests-solvers/Makefile tests-solvers/VectorTests/Makefile tests-solvers/OperatorTests/Makefile tests-solvers/SolverTests/Makefile tests-std-mesh/Makefile tests-std-mesh/Simple/Makefile tests-std-mesh/Readers/Makefile tests-std-framework/Makefile tests-std-framework/Assembly/Makefile tests-std-framework/Problem/Makefile"
 
 
 
@@ -5934,10 +5972,17 @@ echo "$as_me: error: conditional \"HAVE_CHACO\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${BUILD_TESTS_TRUE}" && test -z "${BUILD_TESTS_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"BUILD_TESTS\" was never defined.
+if test -z "${BUILD_CXXTESTS_TRUE}" && test -z "${BUILD_CXXTESTS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_CXXTESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"BUILD_TESTS\" was never defined.
+echo "$as_me: error: conditional \"BUILD_CXXTESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_LOW_LEVEL_TESTS_TRUE}" && test -z "${BUILD_LOW_LEVEL_TESTS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_LOW_LEVEL_TESTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_LOW_LEVEL_TESTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -6477,6 +6522,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
+  "Makefile.internal" ) CONFIG_FILES="$CONFIG_FILES Makefile.internal" ;;
   "Makefile.export" ) CONFIG_FILES="$CONFIG_FILES Makefile.export" ;;
   "Makefile.export.TSFExtended" ) CONFIG_FILES="$CONFIG_FILES Makefile.export.TSFExtended" ;;
   "Makefile.site.sundance" ) CONFIG_FILES="$CONFIG_FILES Makefile.site.sundance" ;;
@@ -6507,7 +6553,6 @@ do
   "tests-std-mesh/Simple/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests-std-mesh/Simple/Makefile" ;;
   "tests-std-mesh/Readers/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests-std-mesh/Readers/Makefile" ;;
   "tests-std-framework/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests-std-framework/Makefile" ;;
-  "tests-std-framework/HomogeneousDOFMap/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests-std-framework/HomogeneousDOFMap/Makefile" ;;
   "tests-std-framework/Assembly/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests-std-framework/Assembly/Makefile" ;;
   "tests-std-framework/Problem/Makefile" ) CONFIG_FILES="$CONFIG_FILES tests-std-framework/Problem/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
@@ -6673,8 +6718,10 @@ s,@USE_ALTERNATE_AR_FALSE@,$USE_ALTERNATE_AR_FALSE,;t t
 s,@ALTERNATE_AR@,$ALTERNATE_AR,;t t
 s,@HAVE_CHACO_TRUE@,$HAVE_CHACO_TRUE,;t t
 s,@HAVE_CHACO_FALSE@,$HAVE_CHACO_FALSE,;t t
-s,@BUILD_TESTS_TRUE@,$BUILD_TESTS_TRUE,;t t
-s,@BUILD_TESTS_FALSE@,$BUILD_TESTS_FALSE,;t t
+s,@BUILD_CXXTESTS_TRUE@,$BUILD_CXXTESTS_TRUE,;t t
+s,@BUILD_CXXTESTS_FALSE@,$BUILD_CXXTESTS_FALSE,;t t
+s,@BUILD_LOW_LEVEL_TESTS_TRUE@,$BUILD_LOW_LEVEL_TESTS_TRUE,;t t
+s,@BUILD_LOW_LEVEL_TESTS_FALSE@,$BUILD_LOW_LEVEL_TESTS_FALSE,;t t
 s,@BUILD_EXAMPLES_TRUE@,$BUILD_EXAMPLES_TRUE,;t t
 s,@BUILD_EXAMPLES_FALSE@,$BUILD_EXAMPLES_FALSE,;t t
 s,@PYTHON_USE_TRUE@,$PYTHON_USE_TRUE,;t t
diff --git a/python/example/Makefile.in b/python/example/Makefile.in
--- a/python/example/Makefile.in
+++ b/python/example/Makefile.in
@@ -96,12 +96,14 @@ AUTOCONF = @AUTOCONF@
 AUTOHEADER = @AUTOHEADER@
 AUTOMAKE = @AUTOMAKE@
 AWK = @AWK@
+BUILD_CXXTESTS_FALSE = @BUILD_CXXTESTS_FALSE@
+BUILD_CXXTESTS_TRUE = @BUILD_CXXTESTS_TRUE@
 BUILD_EXAMPLES_FALSE = @BUILD_EXAMPLES_FALSE@
 BUILD_EXAMPLES_TRUE = @BUILD_EXAMPLES_TRUE@
+BUILD_LOW_LEVEL_TESTS_FALSE = @BUILD_LOW_LEVEL_TESTS_FALSE@
+BUILD_LOW_LEVEL_TESTS_TRUE = @BUILD_LOW_LEVEL_TESTS_TRUE@
 BUILD_PYTHON_FALSE = @BUILD_PYTHON_FALSE@
 BUILD_PYTHON_TRUE = @BUILD_PYTHON_TRUE@
-BUILD_TESTS_FALSE = @BUILD_TESTS_FALSE@
-BUILD_TESTS_TRUE = @BUILD_TESTS_TRUE@
 CC = @CC@
 CCDEPMODE = @CCDEPMODE@
 CFLAGS = @CFLAGS@
@@ -233,16 +235,24 @@ AUTOMAKE_OPTIONS = foreign
 PARAM_FILES = $(srcdir)/aztecSolver.py $(srcdir)/bicgstabSolver.py \
 $(srcdir)/noxSolver.py
 
-EXTRA_DIST = $(PARAM_FILES) setpath.py exPoisson1D.py exPoisson2D.py \
-	exPoisson3D.py exHelmholtz1D.py exRadDiff1D.py
-
+EXTRA_DIST = $(PARAM_FILES) setpath.py $(ALL_PROGS)
 MAINTAINERCLEANFILES = Makefile.in
 
 # Define the suite of examples
-EXAMPLE_SUITE = exPoisson1D exPoisson2D \
-	exPoisson3D exHelmholtz1D exRadDiff1D
-
+PARALLEL_SRC = exPoisson1D exPoisson2D exHelmholtz1D exRadDiff1D
+SERIAL_SRC = exPoisson3D
+ALL_SRC = $(PARALLEL_SRC) $(SERIAL_SRC)
 SETPATH_PY = setpath.py 
+TESTS = $(ALL_PROGS:%.py=%.tst) 
+PTESTS = $(PARALLEL_PROGS:%.py=%.ptst)
+ALL_PROGS = $(PARALLEL_PROGS) $(SERIAL_PROGS)
+PARALLEL_PROGS = $(PARALLEL_SRC:%=%.py)
+SERIAL_PROGS = $(SERIAL_SRC:%=%.py)
+@HAVE_MPI_TRUE@CHECKTEST_ARGS = $(TESTS) $(PTESTS)
+@HAVE_MPI_FALSE@CHECKTEST_ARGS = $(TESTS)
+NPROC = 2
+@HAVE_MPI_TRUE@MPI_COMMAND = mpirun -np $(NPROC)
+@HAVE_MPI_FALSE@MPI_COMMAND = 
 all: all-am
 
 .SUFFIXES:
@@ -283,6 +293,79 @@ ctags: CTAGS
 CTAGS:
 
 
+check-TESTS: $(TESTS)
+	@failed=0; all=0; xfail=0; xpass=0; skip=0; \
+	srcdir=$(srcdir); export srcdir; \
+	list='$(TESTS)'; \
+	if test -n "$$list"; then \
+	  for tst in $$list; do \
+	    if test -f ./$$tst; then dir=./; \
+	    elif test -f $$tst; then dir=; \
+	    else dir="$(srcdir)/"; fi; \
+	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *" $$tst "*) \
+		xpass=`expr $$xpass + 1`; \
+		failed=`expr $$failed + 1`; \
+		echo "XPASS: $$tst"; \
+	      ;; \
+	      *) \
+		echo "PASS: $$tst"; \
+	      ;; \
+	      esac; \
+	    elif test $$? -ne 77; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *" $$tst "*) \
+		xfail=`expr $$xfail + 1`; \
+		echo "XFAIL: $$tst"; \
+	      ;; \
+	      *) \
+		failed=`expr $$failed + 1`; \
+		echo "FAIL: $$tst"; \
+	      ;; \
+	      esac; \
+	    else \
+	      skip=`expr $$skip + 1`; \
+	      echo "SKIP: $$tst"; \
+	    fi; \
+	  done; \
+	  if test "$$failed" -eq 0; then \
+	    if test "$$xfail" -eq 0; then \
+	      banner="All $$all tests passed"; \
+	    else \
+	      banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
+	    fi; \
+	  else \
+	    if test "$$xpass" -eq 0; then \
+	      banner="$$failed of $$all tests failed"; \
+	    else \
+	      banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
+	    fi; \
+	  fi; \
+	  dashes="$$banner"; \
+	  skipped=""; \
+	  if test "$$skip" -ne 0; then \
+	    skipped="($$skip tests were not run)"; \
+	    test `echo "$$skipped" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      dashes="$$skipped"; \
+	  fi; \
+	  report=""; \
+	  if test "$$failed" -ne 0 && test -n "$(PACKAGE_BUGREPORT)"; then \
+	    report="Please report to $(PACKAGE_BUGREPORT)"; \
+	    test `echo "$$report" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      dashes="$$report"; \
+	  fi; \
+	  dashes=`echo "$$dashes" | sed s/./=/g`; \
+	  echo "$$dashes"; \
+	  echo "$$banner"; \
+	  test -z "$$skipped" || echo "$$skipped"; \
+	  test -z "$$report" || echo "$$report"; \
+	  echo "$$dashes"; \
+	  test "$$failed" -eq 0; \
+	else :; fi
+
 distdir: $(DISTFILES)
 	$(mkdir_p) $(distdir)/$(srcdir)
 	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
@@ -312,6 +395,7 @@ distdir: $(DISTFILES)
 	  fi; \
 	done
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 all-am: Makefile
 installdirs:
@@ -384,20 +468,36 @@ ps-am:
 
 uninstall-am: uninstall-info-am
 
-.PHONY: all all-am check check-am clean clean-generic distclean \
-	distclean-generic distdir dvi dvi-am html html-am info info-am \
-	install install-am install-data install-data-am install-exec \
-	install-exec-am install-info install-info-am install-man \
-	install-strip installcheck installcheck-am installdirs \
-	maintainer-clean maintainer-clean-generic mostlyclean \
-	mostlyclean-generic pdf pdf-am ps ps-am uninstall uninstall-am \
-	uninstall-info-am
+.PHONY: all all-am check check-TESTS check-am clean clean-generic \
+	distclean distclean-generic distdir dvi dvi-am html html-am \
+	info info-am install install-am install-data install-data-am \
+	install-exec install-exec-am install-info install-info-am \
+	install-man install-strip installcheck installcheck-am \
+	installdirs maintainer-clean maintainer-clean-generic \
+	mostlyclean mostlyclean-generic pdf pdf-am ps ps-am uninstall \
+	uninstall-am uninstall-info-am
 
 
-all: $(EXAMPLE_SUITE)
+all: $(ALL_SRC)
 	if [ $(top_srcdir) != @abs_top_builddir@ ]; then /bin/cp $(srcdir)/$(SETPATH_PY) $(PARAM_FILES) . ; fi
 
-# Run the example script
+%.tst: %.py
+	./$< > $@ 2>&1
+	echo "done" $@
+
+%.ptst: %.py
+	$(MPI_COMMAND) ./$< > $@ 2>&1
+	echo "done" $@
+
+tests:
+	$(MAKE) $(TESTS)
+	@HAVE_MPI_TRUE@$(MAKE) $(PTESTS)
+	$(top_srcdir)/etc/checkTests.pl $(CHECKTEST_ARGS) 
+
+serialtests:
+	$(MAKE) $(TESTS)
+	$(top_srcdir)/etc/checkTests.pl $(CHECKTEST_ARGS) 
+
 ex%: $(srcdir)/ex%.py
 	if [ $(top_srcdir) != @abs_top_builddir@ ]; then /bin/cp $(srcdir)/$@.py . ; fi
 
diff --git a/tests-core/SymbolicTests/Makefile.in b/tests-core/SymbolicTests/Makefile.in
--- a/tests-core/SymbolicTests/Makefile.in
+++ b/tests-core/SymbolicTests/Makefile.in
@@ -111,11 +111,10 @@ POST_UNINSTALL = :
 build_triplet = @build@
 host_triplet = @host@
 target_triplet = @target@
-noinst_PROGRAMS = SimpleEval$(EXEEXT) PolynomialTest$(EXEEXT) \
-	TestEval$(EXEEXT) StdTransformation$(EXEEXT) \
-	VecOpTest$(EXEEXT) ScalabilityTest$(EXEEXT) \
-	DepthScalabilityTest$(EXEEXT) VecTimings$(EXEEXT) \
-	VariationTest$(EXEEXT)
+noinst_PROGRAMS = $(am__EXEEXT_1) SimpleEval$(EXEEXT) \
+	PolynomialTest$(EXEEXT) StdTransformation$(EXEEXT) \
+	ScalabilityTest$(EXEEXT) DepthScalabilityTest$(EXEEXT) \
+	VecTimings$(EXEEXT) VariationTest$(EXEEXT)
 DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in \
 	$(top_srcdir)/Makefile.common
 subdir = tests-core/SymbolicTests
@@ -137,6 +136,7 @@ mkinstalldirs = $(SHELL) $(top_srcdir)/config/mkinstalldirs
 CONFIG_HEADER = $(top_builddir)/src-solvers/TSF_config.h \
 	$(top_builddir)/src-utils/SundanceConfig.h
 CONFIG_CLEAN_FILES =
+am__EXEEXT_1 = TestEval$(EXEEXT) VecOpTest$(EXEEXT)
 PROGRAMS = $(noinst_PROGRAMS)
 am_DepthScalabilityTest_OBJECTS =  \
 	DepthScalabilityTest-DepthScalabilityTest.$(OBJEXT)
@@ -193,12 +193,14 @@ AUTOCONF = @AUTOCONF@
 AUTOHEADER = @AUTOHEADER@
 AUTOMAKE = @AUTOMAKE@
 AWK = @AWK@
+BUILD_CXXTESTS_FALSE = @BUILD_CXXTESTS_FALSE@
+BUILD_CXXTESTS_TRUE = @BUILD_CXXTESTS_TRUE@
 BUILD_EXAMPLES_FALSE = @BUILD_EXAMPLES_FALSE@
 BUILD_EXAMPLES_TRUE = @BUILD_EXAMPLES_TRUE@
+BUILD_LOW_LEVEL_TESTS_FALSE = @BUILD_LOW_LEVEL_TESTS_FALSE@
+BUILD_LOW_LEVEL_TESTS_TRUE = @BUILD_LOW_LEVEL_TESTS_TRUE@
 BUILD_PYTHON_FALSE = @BUILD_PYTHON_FALSE@
 BUILD_PYTHON_TRUE = @BUILD_PYTHON_TRUE@
-BUILD_TESTS_FALSE = @BUILD_TESTS_FALSE@
-BUILD_TESTS_TRUE = @BUILD_TESTS_TRUE@
 CC = @CC@
 CCDEPMODE = @CCDEPMODE@
 CFLAGS = $(TEUCHOS_CFLAGS)
@@ -327,6 +329,7 @@ target_alias = @target_alias@
 target_cpu = @target_cpu@
 target_os = @target_os@
 target_vendor = @target_vendor@
+TEST_SRC = TestEval VecOpTest
 LIBDEPS = $(top_builddir)/src-core/libsundanceCore.a \
 $(top_builddir)/src-utils/libsundanceUtils.a 
 
@@ -384,6 +387,9 @@ $(top_builddir)/src-utils/libsundanceUtils.a
 
 StdTransformation_CXXFLAGS = $(CORE_INCLUDES) $(TRILINOS_CXXFLAGS)
 StdTransformation_LDADD = $(CORE_LIBS) 
+TEST_EXE = $(TEST_SRC:%=%.exe)
+TESTS = $(TEST_EXE:%.exe=%.tst)
+CHECKTEST_ARGS = $(TESTS)
 SUNDANCE_DIR = $(top_srcdir)
 
 # ------------------------------------------------------------------------
@@ -778,6 +784,79 @@ GTAGS:
 distclean-tags:
 	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
 
+check-TESTS: $(TESTS)
+	@failed=0; all=0; xfail=0; xpass=0; skip=0; \
+	srcdir=$(srcdir); export srcdir; \
+	list='$(TESTS)'; \
+	if test -n "$$list"; then \
+	  for tst in $$list; do \
+	    if test -f ./$$tst; then dir=./; \
+	    elif test -f $$tst; then dir=; \
+	    else dir="$(srcdir)/"; fi; \
+	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *" $$tst "*) \
+		xpass=`expr $$xpass + 1`; \
+		failed=`expr $$failed + 1`; \
+		echo "XPASS: $$tst"; \
+	      ;; \
+	      *) \
+		echo "PASS: $$tst"; \
+	      ;; \
+	      esac; \
+	    elif test $$? -ne 77; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *" $$tst "*) \
+		xfail=`expr $$xfail + 1`; \
+		echo "XFAIL: $$tst"; \
+	      ;; \
+	      *) \
+		failed=`expr $$failed + 1`; \
+		echo "FAIL: $$tst"; \
+	      ;; \
+	      esac; \
+	    else \
+	      skip=`expr $$skip + 1`; \
+	      echo "SKIP: $$tst"; \
+	    fi; \
+	  done; \
+	  if test "$$failed" -eq 0; then \
+	    if test "$$xfail" -eq 0; then \
+	      banner="All $$all tests passed"; \
+	    else \
+	      banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
+	    fi; \
+	  else \
+	    if test "$$xpass" -eq 0; then \
+	      banner="$$failed of $$all tests failed"; \
+	    else \
+	      banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
+	    fi; \
+	  fi; \
+	  dashes="$$banner"; \
+	  skipped=""; \
+	  if test "$$skip" -ne 0; then \
+	    skipped="($$skip tests were not run)"; \
+	    test `echo "$$skipped" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      dashes="$$skipped"; \
+	  fi; \
+	  report=""; \
+	  if test "$$failed" -ne 0 && test -n "$(PACKAGE_BUGREPORT)"; then \
+	    report="Please report to $(PACKAGE_BUGREPORT)"; \
+	    test `echo "$$report" | wc -c` -le `echo "$$banner" | wc -c` || \
+	      dashes="$$report"; \
+	  fi; \
+	  dashes=`echo "$$dashes" | sed s/./=/g`; \
+	  echo "$$dashes"; \
+	  echo "$$banner"; \
+	  test -z "$$skipped" || echo "$$skipped"; \
+	  test -z "$$report" || echo "$$report"; \
+	  echo "$$dashes"; \
+	  test "$$failed" -eq 0; \
+	else :; fi
+
 distdir: $(DISTFILES)
 	$(mkdir_p) $(distdir)/../..
 	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
@@ -807,6 +886,7 @@ distdir: $(DISTFILES)
 	  fi; \
 	done
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 all-am: Makefile $(PROGRAMS)
 installdirs:
@@ -883,17 +963,29 @@ ps-am:
 
 uninstall-am: uninstall-info-am
 
-.PHONY: CTAGS GTAGS all all-am check check-am clean clean-generic \
-	clean-noinstPROGRAMS ctags distclean distclean-compile \
-	distclean-generic distclean-tags distdir dvi dvi-am html \
-	html-am info info-am install install-am install-data \
-	install-data-am install-exec install-exec-am install-info \
-	install-info-am install-man install-strip installcheck \
-	installcheck-am installdirs maintainer-clean \
+.PHONY: CTAGS GTAGS all all-am check check-TESTS check-am clean \
+	clean-generic clean-noinstPROGRAMS ctags distclean \
+	distclean-compile distclean-generic distclean-tags distdir dvi \
+	dvi-am html html-am info info-am install install-am \
+	install-data install-data-am install-exec install-exec-am \
+	install-info install-info-am install-man install-strip \
+	installcheck installcheck-am installdirs maintainer-clean \
 	maintainer-clean-generic mostlyclean mostlyclean-compile \
 	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
 	uninstall-am uninstall-info-am
 
+
+%.tst : %.exe
+	./$< > $@ 2>&1 
+	echo "done" $@
+
+tests:
+	$(MAKE) $(TESTS)
+	$(top_srcdir)/etc/checkTests.pl $(CHECKTEST_ARGS) 
+
+serialtests:
+	$(MAKE) $(TESTS)
+	$(top_srcdir)/etc/checkTests.pl $(CHECKTEST_ARGS) 
 
 # ------------------------------------------------------------------------
 #
@@ -902,35 +994,6 @@ uninstall-am: uninstall-info-am
 include $(top_builddir)/Makefile.site.sundance
 include $(top_builddir)/Makefile.export.TSFExtended
 include $(TRILINOS_DIR)/packages/teuchos/Makefile.export
-
-#ListEval_SOURCES = $(srcdir)/ListEval.cpp 
-#
-#ListEval_DEPENDENCIES = $(top_builddir)/src-core/libsundanceCore.a \
-#$(top_builddir)/src-utils/libsundanceUtils.a 
-#
-#ListEval_CXXFLAGS = $(CORE_INCLUDES)
-#
-#ListEval_LDADD = $(CORE_LIBS) 
-#
-#
-#Integrals_SOURCES = $(srcdir)/Integrals.cpp 
-#
-#Integrals_DEPENDENCIES = $(top_builddir)/src-core/libsundanceCore.a \
-#$(top_builddir)/src-utils/libsundanceUtils.a 
-#
-#Integrals_CXXFLAGS = $(CORE_INCLUDES)
-#
-#Integrals_LDADD = $(CORE_LIBS)
-#
-#
-#EvalCache_SOURCES = $(srcdir)/EvalCache.cpp 
-#
-#EvalCache_DEPENDENCIES = $(top_builddir)/src-core/libsundanceCore.a \
-#$(top_builddir)/src-utils/libsundanceUtils.a 
-#
-#EvalCache_CXXFLAGS = $(CORE_INCLUDES)
-#
-#EvalCache_LDADD = $(CORE_LIBS) 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
 .NOEXPORT:
